# Generated by Django 6.0.5 on 2026-06-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=100)),
                ('duracao', models.CharField(max_length=100)),
            ],
        ),
    ]
